# Generated by Django 6.0 on 2026-07-31 00:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dms', '0015_dmsprojectconfig_file_gate_require_sides'),
        ('projects', '0006_add_structure_scout_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutDetectionState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type_code', models.CharField(blank=True, default='', max_length=40)),
                ('encoding_code', models.CharField(blank=True, default='utf-8', max_length=40)),
                ('line_ending_code', models.CharField(blank=True, default='lf', max_length=10)),
                ('delimiter', models.CharField(blank=True, default='', max_length=8)),
                ('has_header', models.BooleanField(default=True)),
                ('header_row', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('confidence', models.CharField(blank=True, choices=[('high', 'Alta'), ('medium', 'Media'), ('low', 'Baja')], default='', max_length=16)),
                ('status', models.CharField(choices=[('idle', 'Sin confirmar'), ('draft_ready', 'Listo'), ('needs_review', 'Requiere revisión'), ('failed', 'Fallido')], default='idle', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('suggestions_snapshot', models.JSONField(blank=True, default=dict)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scout_detections_confirmed', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scout_detection', to='projects.project')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scout_detections', to='dms.dmssamplefile')),
            ],
            options={
                'verbose_name': 'Detección STRUCTURE SCOUT',
                'verbose_name_plural': 'Detecciones STRUCTURE SCOUT',
            },
        ),
    ]
