# Generated by Django 6.0 on 2026-07-31 00:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0015_dmsprojectconfig_file_gate_require_sides'),
        ('projects', '0006_add_structure_scout_kind'),
        ('structure_scout', '0001_scout_detection_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutFieldsState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fields', models.JSONField(blank=True, default=list)),
                ('confidence', models.CharField(blank=True, choices=[('high', 'Alta'), ('medium', 'Media'), ('low', 'Baja')], default='', max_length=16)),
                ('status', models.CharField(choices=[('idle', 'Sin confirmar'), ('draft_ready', 'Listo'), ('needs_review', 'Requiere revisión'), ('failed', 'Fallido')], default='idle', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scout_fields_confirmed', to=settings.AUTH_USER_MODEL)),
                ('detection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields_states', to='structure_scout.scoutdetectionstate')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scout_fields', to='projects.project')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scout_fields_states', to='dms.dmssamplefile')),
            ],
            options={
                'verbose_name': 'Campos STRUCTURE SCOUT',
                'verbose_name_plural': 'Campos STRUCTURE SCOUT',
            },
        ),
    ]
