# Generated by Django 6.0 on 2026-07-31 01:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0015_dmsprojectconfig_file_gate_require_sides'),
        ('projects', '0006_add_structure_scout_kind'),
        ('structure_scout', '0002_scout_fields_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('is_current', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft_ready', 'Listo'), ('needs_review', 'Requiere revisión')], default='draft_ready', max_length=20)),
                ('confidence', models.CharField(blank=True, choices=[('high', 'Alta'), ('medium', 'Media'), ('low', 'Baja')], default='', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('sample_filename', models.CharField(blank=True, default='', max_length=255)),
                ('sample_hash_short', models.CharField(blank=True, default='', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_drafts_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_drafts', to='projects.project')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_drafts', to='dms.dmssamplefile')),
            ],
            options={
                'verbose_name': 'Borrador STRUCTURE SCOUT',
                'verbose_name_plural': 'Borradores STRUCTURE SCOUT',
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('project', 'version'), name='structure_scout_draft_project_version_uniq')],
            },
        ),
    ]
