# Generated by Django 6.0 on 2026-07-31 01:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_add_structure_scout_kind'),
        ('structure_scout', '0003_structure_draft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutApply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draft_version', models.PositiveIntegerField(default=0)),
                ('target_kind', models.CharField(choices=[('file_gate', 'FILE GATE'), ('reverse', 'Reverse Studio')], max_length=40)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('failed', 'Fallido')], default='ok', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scout_applies_created', to=settings.AUTH_USER_MODEL)),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applies', to='structure_scout.structuredraft')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scout_applies', to='projects.project')),
                ('target_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scout_applies_received', to='projects.project')),
            ],
            options={
                'verbose_name': 'Apply STRUCTURE SCOUT',
                'verbose_name_plural': 'Applies STRUCTURE SCOUT',
                'ordering': ['-created_at'],
            },
        ),
    ]
