# Generated by Django 6.0 on 2026-08-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structure_scout", "0004_scout_apply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scoutapply",
            name="target_kind",
            field=models.CharField(
                choices=[
                    ("file_gate", "FILE GATE"),
                    ("reverse", "Reverse Studio"),
                    ("file_match", "FILE MATCH"),
                    ("file_clean", "FILE CLEAN"),
                    ("dms", "FilePipe"),
                    ("file_split_merge", "FILE SPLIT/MERGE"),
                ],
                max_length=40,
            ),
        ),
    ]
