# Generated by Django 6.0 on 2026-08-12 15:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dms', '0016_transform_ops_numeric_integer'),
        ('projects', '0008_add_file_split_merge_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitMergeJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('published_version_number', models.PositiveIntegerField()),
                ('operation', models.CharField(choices=[('split', 'Split'), ('merge', 'Merge')], max_length=16)),
                ('status', models.CharField(choices=[('queued', 'En cola'), ('running', 'En curso'), ('completed', 'Completado'), ('failed', 'Fallido')], default='running', max_length=16)),
                ('dry_run', models.BooleanField(default=False)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('inputs', models.JSONField(blank=True, default=list)),
                ('outputs', models.JSONField(blank=True, default=list)),
                ('manifest_path', models.CharField(blank=True, default='', max_length=512)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('preview', models.JSONField(blank=True, default=dict)),
                ('rules_snapshot', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_split_merge_jobs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_split_merge_jobs', to='projects.project')),
                ('published_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_split_merge_jobs', to='dms.dmsmappingversion')),
            ],
            options={
                'verbose_name': 'FILE SPLIT/MERGE — Job',
                'verbose_name_plural': 'FILE SPLIT/MERGE — Jobs',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('project', 'idempotency_key'), name='file_sm_job_idempotency_uniq')],
            },
        ),
    ]
