# Generated by Django 6.0 on 2026-07-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='records_expand_display',
            field=models.JSONField(blank=True, default=dict, help_text='Tema visual de la tabla expandida de registros (record_expand).'),
        ),
    ]
