# Generated by Django 6.0 on 2026-07-06

import uuid

from django.db import migrations, models
import django.db.models.deletion


LEGACY_PRESETS = {
    "excel_gray": {
        "table_classes": [
            "cell-border", "compact", "stripe", "hover", "order-column", "nowrap",
        ],
        "header_bg": "#e8eef4",
        "header_color": "#1a1d21",
        "header_border": "#c5cdd8",
        "cell_border": "#d4d9e0",
        "stripe_bg": "#f7f9fb",
        "hover_bg": "#e8eef4",
        "page_length": 25,
    },
    "inventory_red": {
        "table_classes": [
            "cell-border", "compact", "stripe", "hover", "order-column", "nowrap",
        ],
        "header_bg": "#c62828",
        "header_color": "#ffffff",
        "header_border": "#b71c1c",
        "cell_border": "#e0e0e0",
        "stripe_bg": "#f5f5f5",
        "hover_bg": "#ffebee",
        "page_length": 25,
    },
}

CLASS_TO_FIELD = {
    "cell-border": "grid_cell_border",
    "compact": "layout_compact",
    "stripe": "row_stripe",
    "hover": "row_hover",
    "order-column": "column_order_highlight",
    "nowrap": "cell_nowrap",
}


def migrate_json_to_theme(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Theme = apps.get_model("projects", "ProjectRecordsExpandTheme")

    for project in Project.objects.all():
        stored = project.records_expand_display or {}
        if not stored:
            continue

        preset = stored.get("preset") or "excel_gray"
        if preset == "custom":
            base = dict(LEGACY_PRESETS["excel_gray"])
        else:
            base = dict(LEGACY_PRESETS.get(preset, LEGACY_PRESETS["excel_gray"]))

        table_classes = stored.get("table_classes") or base["table_classes"]
        for key in (
            "header_bg", "header_color", "header_border",
            "cell_border", "stripe_bg", "hover_bg", "page_length",
        ):
            if key in stored and stored[key] is not None:
                base[key] = stored[key]

        booleans = {field: False for field in CLASS_TO_FIELD.values()}
        for class_name in table_classes:
            field_name = CLASS_TO_FIELD.get(class_name)
            if field_name:
                booleans[field_name] = True

        Theme.objects.create(
            project=project,
            header_bg=base["header_bg"],
            header_color=base["header_color"],
            header_border=base["header_border"],
            cell_border=base["cell_border"],
            stripe_bg=base["stripe_bg"],
            hover_bg=base["hover_bg"],
            page_length=int(base["page_length"]),
            **booleans,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_records_expand_display"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectRecordsExpandTheme",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("header_bg", models.CharField(default="#e8eef4", max_length=7)),
                ("header_color", models.CharField(default="#1a1d21", max_length=7)),
                ("header_border", models.CharField(default="#c5cdd8", max_length=7)),
                ("cell_border", models.CharField(default="#d4d9e0", max_length=7)),
                ("stripe_bg", models.CharField(default="#f7f9fb", max_length=7)),
                ("hover_bg", models.CharField(default="#e8eef4", max_length=7)),
                ("grid_cell_border", models.BooleanField(default=True)),
                ("layout_compact", models.BooleanField(default=True)),
                ("row_stripe", models.BooleanField(default=True)),
                ("row_hover", models.BooleanField(default=True)),
                ("column_order_highlight", models.BooleanField(default=True)),
                ("cell_nowrap", models.BooleanField(default=True)),
                ("page_length", models.PositiveSmallIntegerField(default=25)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expand_theme",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tema tabla expandida de registros",
                "verbose_name_plural": "Temas tabla expandida de registros",
            },
        ),
        migrations.AddConstraint(
            model_name="projectrecordsexpandtheme",
            constraint=models.CheckConstraint(
                condition=models.Q(("page_length__gte", 10), ("page_length__lte", 100)),
                name="projects_expandtheme_page_length_range",
            ),
        ),
        migrations.RunPython(migrate_json_to_theme, noop_reverse),
        migrations.RemoveField(
            model_name="project",
            name="records_expand_display",
        ),
    ]
