# Generated by Django 6.0 on 2026-07-13 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('projects', '0003_projectrecordsexpandtheme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_kind',
            field=models.CharField(choices=[('workspace', 'Workspace (tabla)'), ('dms', 'DMS (FilePipe)')], default='workspace', max_length=16),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['company', 'project_kind'], name='projects_pr_company_ac4c6a_idx'),
        ),
    ]
