# Generated by Django 6.0 on 2026-07-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_add_project_kind_and_dms_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_kind',
            field=models.CharField(choices=[('workspace', 'Workspace (tabla)'), ('dms', 'DMS (FilePipe)'), ('file_gate', 'FILE GATE (Validador)'), ('reverse', 'Reverse Studio (Emisor)'), ('file_match', 'FILE MATCH (Conciliador)')], default='workspace', max_length=16),
        ),
    ]
