# Generated by Django 6.0 on 2026-07-29 23:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dms', '0014_dmsprojectconfig_file_gate_bridge'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMatchSourceB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type_code', models.CharField(blank=True, default='', max_length=32)),
                ('capture_start', models.JSONField(blank=True, default=dict)),
                ('capture_end', models.JSONField(blank=True, default=dict)),
                ('content_rules', models.JSONField(blank=True, default=dict)),
                ('processing_report', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('fields', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_source_b', to='dms.dmsmappingversion')),
            ],
            options={
                'verbose_name': 'FILE MATCH — Perfil B',
                'verbose_name_plural': 'FILE MATCH — Perfiles B',
            },
        ),
    ]
