# Generated by Django 6.0 on 2026-07-29 23:48

import apps.file_match.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0014_dmsprojectconfig_file_gate_bridge'),
        ('file_match', '0001_file_match_source_b'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMatchRules',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rules', models.JSONField(blank=True, default=apps.file_match.models.default_match_rules)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_rules', to='dms.dmsmappingversion')),
            ],
            options={
                'verbose_name': 'FILE MATCH — Reglas de cruce',
                'verbose_name_plural': 'FILE MATCH — Reglas de cruce',
            },
        ),
    ]
