# Generated by Django 6.0 on 2026-07-30 00:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0014_dmsprojectconfig_file_gate_bridge'),
        ('file_match', '0002_file_match_rules'),
        ('projects', '0005_file_match_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMatchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('published_version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('running', 'En curso'), ('completed', 'Completado'), ('failed', 'Fallido'), ('partial', 'Parcial')], default='running', max_length=16)),
                ('verdict', models.CharField(blank=True, choices=[('passed', 'Cuadra'), ('failed', 'No cuadra'), ('partial', 'Parcial')], default='', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('file_a_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_a_path', models.CharField(blank=True, default='', max_length=512)),
                ('file_a_size_bytes', models.BigIntegerField(default=0)),
                ('file_a_hash', models.CharField(blank=True, default='', max_length=64)),
                ('file_b_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_b_path', models.CharField(blank=True, default='', max_length=512)),
                ('file_b_size_bytes', models.BigIntegerField(default=0)),
                ('file_b_hash', models.CharField(blank=True, default='', max_length=64)),
                ('rules_snapshot', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('detail_preview', models.JSONField(blank=True, default=list)),
                ('report_path', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_match_jobs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_match_jobs', to='projects.project')),
                ('published_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_match_jobs', to='dms.dmsmappingversion')),
            ],
            options={
                'verbose_name': 'FILE MATCH — Job',
                'verbose_name_plural': 'FILE MATCH — Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
