# Generated by Django 6.0 on 2026-07-31 22:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0006_add_structure_scout_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSeedEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_slot', models.CharField(default='profile_a', max_length=40)),
                ('source_kind', models.CharField(max_length=40)),
                ('source_slot', models.CharField(default='schema', max_length=40)),
                ('source_version', models.PositiveIntegerField(default=0)),
                ('source_slug', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('failed', 'Fallido')], default='ok', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('mode', models.CharField(default='clone_snapshot', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_seed_events_created', to=settings.AUTH_USER_MODEL)),
                ('source_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_seed_events_as_source', to='projects.project')),
                ('target_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_seed_events', to='projects.project')),
            ],
            options={
                'verbose_name': 'PROFILE SEED event',
                'verbose_name_plural': 'PROFILE SEED events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_project', '-created_at'], name='ps_event_target_created_idx')],
            },
        ),
    ]
