# Generated by Django 6.0 on 2026-07-13 15:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0002_seed_catalogs'),
        ('projects', '0003_projectrecordsexpandtheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='DmsProjectConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visibility', models.CharField(choices=[('company', 'Público (compañía)'), ('members_only', 'Privado')], default='members_only', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dms_config', to='projects.project')),
            ],
            options={
                'verbose_name': 'Configuración DMS de proyecto',
                'verbose_name_plural': 'Configuraciones DMS de proyecto',
            },
        ),
    ]
