# Generated by Django 6.0 on 2026-07-13 16:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0003_add_project_kind_and_dms_config'),
        ('projects', '0004_add_project_kind_and_dms_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DmsMappingVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicada'), ('archived', 'Archivada')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dms_versions', to='projects.project')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dms_versions_published', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versión DMS de mapping',
                'verbose_name_plural': 'Versiones DMS de mapping',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='dmsprojectconfig',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dms.dmsmappingversion'),
        ),
        migrations.CreateModel(
            name='DmsSourceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type_code', models.CharField(blank=True, default='', max_length=32)),
                ('capture_start', models.JSONField(blank=True, default=dict)),
                ('capture_end', models.JSONField(blank=True, default=dict)),
                ('content_rules', models.JSONField(blank=True, default=dict)),
                ('processing_report', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('fields', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source_profile', to='dms.dmsmappingversion')),
            ],
            options={
                'verbose_name': 'Perfil de origen DMS',
                'verbose_name_plural': 'Perfiles de origen DMS',
            },
        ),
        migrations.AddIndex(
            model_name='dmsmappingversion',
            index=models.Index(fields=['project', 'status'], name='dms_dmsmapp_project_58c42b_idx'),
        ),
        migrations.AddConstraint(
            model_name='dmsmappingversion',
            constraint=models.UniqueConstraint(fields=('project', 'version_number'), name='dms_mappingversion_project_version_uniq'),
        ),
    ]
