# Generated by Django 6.0 on 2026-07-13 21:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0004_mapping_version_and_source_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DmsTargetProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type_code', models.CharField(blank=True, default='', max_length=32)),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('serialization', models.JSONField(blank=True, default=dict)),
                ('write_validation', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('fields', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='target_profile', to='dms.dmsmappingversion')),
            ],
            options={
                'verbose_name': 'Perfil de destino DMS',
                'verbose_name_plural': 'Perfiles de destino DMS',
            },
        ),
    ]
