# Generated by Django 6.0

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dms", "0005_target_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="DmsFieldMappingSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("mappings", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_mapping_set",
                        to="dms.dmsmappingversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conjunto de mapeos DMS",
                "verbose_name_plural": "Conjuntos de mapeos DMS",
            },
        ),
    ]
