# Generated by Django 6.0 on 2026-07-15 22:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0007_file_intake'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueGeneratorType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolver_key', models.CharField(max_length=120)),
                ('param_schema', models.JSONField(blank=True, null=True)),
                ('phase', models.CharField(choices=[('mvp', 'MVP'), ('phase_2', 'Fase 2')], default='mvp', max_length=16)),
            ],
            options={
                'verbose_name': 'Tipo de generador de valor',
                'verbose_name_plural': 'Tipos de generador de valor',
                'ordering': ['sort_order', 'code'],
                'abstract': False,
            },
        ),
    ]
