# Generated by Django 6.0 on 2026-07-16 01:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0011_seed_permission_and_transform_catalogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransformPipelineTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Plantilla de pipeline',
                'verbose_name_plural': 'Plantillas de pipeline',
                'ordering': ['sort_order', 'code'],
                'abstract': False,
            },
        ),
    ]
