# Generated by Django 6.0 on 2026-08-23 17:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('prod', 'Producción')], default='sandbox', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('revoked', 'Revocado')], default='active', max_length=16)),
                ('scopes', models.JSONField(default=list)),
                ('public_id', models.CharField(max_length=16, unique=True)),
                ('secret_hash', models.CharField(max_length=64)),
                ('key_hint', models.CharField(blank=True, default='', max_length=8)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_clients', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_clients_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente API',
                'verbose_name_plural': 'Clientes API',
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('company', 'code'), name='platform_api_unique_code_per_company')],
            },
        ),
    ]
