# Generated by Django 6.0.6 on 2026-09-03 23:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('file_pipeline', '0009_pipelinerun_parent_job_id_and_more'),
        ('projects', '0009_add_role_consulta_generar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('description', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('members_only', 'Privado'), ('company', 'Público')], default='members_only', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('in_progress', 'En proceso'), ('inactive', 'Inactivo'), ('archived', 'Archivado')], default='in_progress', max_length=20)),
                ('source_kind', models.CharField(blank=True, choices=[('sftp', 'SFTP'), ('managed_folder', 'Carpeta gestionada'), ('api_push', 'API / push')], default='', max_length=32)),
                ('filename_pattern', models.CharField(blank=True, default='*', max_length=200)),
                ('sftp_host', models.CharField(blank=True, default='', max_length=255)),
                ('sftp_port', models.PositiveIntegerField(blank=True, null=True)),
                ('sftp_username', models.CharField(blank=True, default='', max_length=128)),
                ('sftp_secret_ref', models.CharField(blank=True, default='', max_length=128)),
                ('sftp_remote_path', models.CharField(blank=True, default='', max_length=500)),
                ('poll_interval_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('after_detect', models.CharField(blank=True, choices=[('leave', 'Dejar'), ('mark', 'Marcar'), ('delete_remote', 'Borrar remoto'), ('move_processed', 'Mover a procesados'), ('delete', 'Borrar')], default='', max_length=32)),
                ('folder_rel_path', models.CharField(blank=True, default='', max_length=500)),
                ('accept_multipart', models.BooleanField(default=True)),
                ('accept_storage_ref', models.BooleanField(default=False)),
                ('push_token_hint', models.CharField(blank=True, default='', max_length=16)),
                ('source_saved_at', models.DateTimeField(blank=True, null=True)),
                ('source_last_test_ok', models.BooleanField(blank=True, null=True)),
                ('settle_seconds', models.PositiveIntegerField(default=5)),
                ('max_bytes', models.BigIntegerField(default=104857600)),
                ('pending_pick_policy', models.CharField(choices=[('fifo', 'FIFO'), ('lifo', 'LIFO')], default='fifo', max_length=8)),
                ('retain_consumed_days', models.PositiveIntegerField(default=90)),
                ('intake_policy_saved_at', models.DateTimeField(blank=True, null=True)),
                ('route_mode', models.CharField(blank=True, choices=[('job', 'Job de app'), ('pipeline', 'Pipeline'), ('defer', 'Diferir')], default='', max_length=20)),
                ('route_kind', models.CharField(blank=True, default='', max_length=32)),
                ('route_saved_at', models.DateTimeField(blank=True, null=True)),
                ('fire_mode', models.CharField(blank=True, choices=[('on_arrival', 'Al llegar'), ('pending_only', 'Solo pendiente')], default='', max_length=20)),
                ('fire_saved_at', models.DateTimeField(blank=True, null=True)),
                ('dup_policy', models.CharField(choices=[('skip', 'Omitir'), ('allow', 'Permitir'), ('replace_pending', 'Sustituir pendiente')], default='skip', max_length=20)),
                ('dup_window_days', models.PositiveIntegerField(default=365)),
                ('retry_max', models.PositiveIntegerField(default=3)),
                ('retry_backoff_sec', models.PositiveIntegerField(default=60)),
                ('quota_max_pending', models.PositiveIntegerField(default=50)),
                ('quota_max_arrivals_per_day', models.PositiveIntegerField(default=200)),
                ('quota_max_bytes_per_day', models.BigIntegerField(default=0)),
                ('idempotency_saved_at', models.DateTimeField(blank=True, null=True)),
                ('notify_enabled', models.BooleanField(default=False)),
                ('notify_on_intake_failed', models.BooleanField(default=True)),
                ('notify_on_fire_failed', models.BooleanField(default=True)),
                ('notify_on_run_failed', models.BooleanField(default=True)),
                ('notify_on_skip', models.BooleanField(default=False)),
                ('notify_channel', models.CharField(blank=True, default='', max_length=16)),
                ('notify_user_ids', models.JSONField(blank=True, default=list)),
                ('notify_webhook_url', models.CharField(blank=True, default='', max_length=500)),
                ('notify_webhook_secret', models.CharField(blank=True, default='', max_length=128)),
                ('notify_saved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='watches', to='company.company')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_watches', to=settings.AUTH_USER_MODEL)),
                ('route_pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watch_routes', to='file_pipeline.pipelinedefinition')),
                ('route_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watch_routes', to='projects.project')),
            ],
            options={
                'verbose_name': 'Bandeja vigilada',
                'verbose_name_plural': 'Bandejas vigiladas',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('watch.created', 'Creado'), ('watch.updated', 'Actualizado'), ('watch.paused', 'Pausado'), ('watch.resumed', 'Reanudado'), ('watch.archived', 'Archivado'), ('watch.source_updated', 'Origen actualizado'), ('watch.source_tested', 'Origen probado'), ('watch.push_token_rotated', 'Token push rotado'), ('watch.route_updated', 'Enrutado actualizado'), ('watch.fire_updated', 'Disparo actualizado'), ('watch.intake_policy_updated', 'Política intake actualizada'), ('watch.idempotency_updated', 'Idempotencia actualizada'), ('watch.notify_updated', 'Avisos actualizados'), ('watch.batch_ingested', 'Lote ingerido'), ('watch.batch_skipped', 'Lote omitido'), ('watch.batch_intake_failed', 'Intake fallido'), ('watch.batch_claim', 'Lote reclamado'), ('watch.fired', 'Disparado'), ('watch.fire_failed', 'Disparo fallido'), ('watch.fire_skipped', 'Disparo omitido'), ('watch.retry_scheduled', 'Reintento programado'), ('watch.notify_sent', 'Aviso enviado')], max_length=48)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watch_audit_events', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='watch_audit_events', to='company.company')),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='file_watch.watch')),
            ],
            options={
                'verbose_name': 'Evento de auditoría de bandeja',
                'verbose_name_plural': 'Eventos de auditoría de bandeja',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(blank=True, default='', max_length=500)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('storage_key', models.CharField(blank=True, default='', max_length=500)),
                ('byte_size', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('claimed', 'Reservado'), ('consumed', 'Consumido'), ('intake_failed', 'Falló intake'), ('skipped', 'Omitido')], default='pending', max_length=20)),
                ('source_kind', models.CharField(blank=True, default='', max_length=32)),
                ('detected_at', models.DateTimeField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_by', models.CharField(blank=True, default='', max_length=128)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('job_id', models.CharField(blank=True, default='', max_length=36)),
                ('pipeline_run_id', models.CharField(blank=True, default='', max_length=36)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='watch_batches', to='company.company')),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='file_watch.watch')),
            ],
            options={
                'verbose_name': 'Lote de bandeja',
                'verbose_name_plural': 'Lotes de bandeja',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('PA', 'Admin de bandeja'), ('ED', 'Editor'), ('GE', 'Ejecutor'), ('CO', 'Consulta')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watch_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_memberships', to=settings.AUTH_USER_MODEL)),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='file_watch.watch')),
            ],
            options={
                'verbose_name': 'Membresía de bandeja',
                'verbose_name_plural': 'Membresías de bandeja',
            },
        ),
        migrations.CreateModel(
            name='WatchNotifyDispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('intake_failed', 'Intake fallido'), ('fire_failed', 'Disparo fallido'), ('run_failed', 'Run fallido'), ('skip', 'Omitido')], max_length=20)),
                ('ref_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_dispatches', to='file_watch.watch')),
            ],
            options={
                'verbose_name': 'Envío de aviso de bandeja',
                'verbose_name_plural': 'Envíos de aviso de bandeja',
            },
        ),
        migrations.AddIndex(
            model_name='watch',
            index=models.Index(fields=['company', 'slug'], name='file_watch__company_b1ef73_idx'),
        ),
        migrations.AddIndex(
            model_name='watch',
            index=models.Index(fields=['company', 'status'], name='file_watch__company_fb4971_idx'),
        ),
        migrations.AddConstraint(
            model_name='watch',
            constraint=models.UniqueConstraint(fields=('company', 'slug'), name='file_watch_company_slug_uniq'),
        ),
        migrations.AddIndex(
            model_name='watchauditevent',
            index=models.Index(fields=['watch', '-created_at'], name='file_watch__watch_i_df3f26_idx'),
        ),
        migrations.AddIndex(
            model_name='watchbatch',
            index=models.Index(fields=['watch', 'status', '-ingested_at'], name='file_watch__watch_i_b35979_idx'),
        ),
        migrations.AddIndex(
            model_name='watchbatch',
            index=models.Index(fields=['watch', 'content_hash'], name='file_watch__watch_i_12f517_idx'),
        ),
        migrations.AddIndex(
            model_name='watchbatch',
            index=models.Index(fields=['company', '-created_at'], name='file_watch__company_ad8699_idx'),
        ),
        migrations.AddIndex(
            model_name='watchmembership',
            index=models.Index(fields=['watch', 'user', 'is_active'], name='file_watch__watch_i_a1e882_idx'),
        ),
        migrations.AddConstraint(
            model_name='watchmembership',
            constraint=models.UniqueConstraint(fields=('watch', 'user'), name='file_watch_membership_user_uniq'),
        ),
        migrations.AddConstraint(
            model_name='watchnotifydispatch',
            constraint=models.UniqueConstraint(fields=('watch', 'kind', 'ref_id'), name='file_watch_notify_ref_uniq'),
        ),
    ]
