# Generated by Django 6.0 on 2026-09-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_watch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='push_token',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
