# Generated by Django 6.0 on 2026-08-21 22:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('description', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('members_only', 'Privado'), ('company', 'Público')], default='members_only', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('in_progress', 'En proceso'), ('inactive', 'Inactivo')], default='in_progress', max_length=20)),
                ('draft_step_labels', models.JSONField(blank=True, default=list)),
                ('design_saved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pipeline_definitions', to='company.company')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_pipelines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pipeline',
                'verbose_name_plural': 'Pipelines',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('PA', 'Admin de pipeline'), ('ED', 'Editor'), ('GE', 'Ejecutor'), ('CO', 'Consulta')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='file_pipeline.pipelinedefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membresía de pipeline',
                'verbose_name_plural': 'Membresías de pipeline',
            },
        ),
        migrations.AddIndex(
            model_name='pipelinedefinition',
            index=models.Index(fields=['company', 'slug'], name='file_pipeli_company_340ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinedefinition',
            index=models.Index(fields=['company', 'status'], name='file_pipeli_company_04b55b_idx'),
        ),
        migrations.AddConstraint(
            model_name='pipelinedefinition',
            constraint=models.UniqueConstraint(fields=('company', 'slug'), name='file_pipeline_def_company_slug_uniq'),
        ),
        migrations.AddIndex(
            model_name='pipelinemembership',
            index=models.Index(fields=['pipeline', 'user', 'is_active'], name='file_pipeli_pipelin_3e6598_idx'),
        ),
        migrations.AddConstraint(
            model_name='pipelinemembership',
            constraint=models.UniqueConstraint(fields=('pipeline', 'user'), name='file_pipeline_membership_user_uniq'),
        ),
    ]
