# Generated by Django 6.0 on 2026-08-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_pipeline', '0001_pipeline_m1'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinedefinition',
            name='draft_steps',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
