# Generated by Django 6.0 on 2026-08-21 23:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_pipeline', '0003_pipeline_m2b_step_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicada')], default='published', max_length=20)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='file_pipeline.pipelinedefinition')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_versions_published', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versión de pipeline',
                'verbose_name_plural': 'Versiones de pipeline',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='pipelinedefinition',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='file_pipeline.pipelineversion'),
        ),
        migrations.AddConstraint(
            model_name='pipelineversion',
            constraint=models.UniqueConstraint(fields=('pipeline', 'version_number'), name='file_pipeline_version_number_uniq'),
        ),
    ]
