# Generated by Django 6.0 on 2026-08-21 23:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_pipeline', '0004_pipeline_m3_publish'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_source', models.CharField(choices=[('ui', 'UI'), ('api', 'API'), ('watch', 'Watch'), ('scheduler', 'Scheduler'), ('dependency', 'Dependencia')], default='ui', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'En cola'), ('running', 'En curso'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='queued', max_length=20)),
                ('dry_run', models.BooleanField(default=False)),
                ('input_filename', models.CharField(blank=True, default='', max_length=255)),
                ('input_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('failed_step_order', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='file_pipeline.pipelinedefinition')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_runs_triggered', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='file_pipeline.pipelineversion')),
            ],
            options={
                'verbose_name': 'Corrida de pipeline',
                'verbose_name_plural': 'Corridas de pipeline',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStepRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('kind', models.CharField(max_length=64)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('project_slug', models.CharField(blank=True, default='', max_length=220)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En curso'), ('completed', 'Completado'), ('failed', 'Fallido'), ('skipped', 'Omitido')], default='pending', max_length=20)),
                ('app_job_id', models.CharField(blank=True, default='', max_length=64)),
                ('error_code', models.CharField(blank=True, default='', max_length=80)),
                ('user_message', models.CharField(blank=True, default='', max_length=500)),
                ('skip_reason', models.CharField(blank=True, default='', max_length=80)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('artifacts', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='file_pipeline.pipelinerun')),
            ],
            options={
                'verbose_name': 'Paso de corrida',
                'verbose_name_plural': 'Pasos de corrida',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='pipelinerun',
            index=models.Index(fields=['pipeline', '-created_at'], name='file_pipeli_pipelin_474cab_idx'),
        ),
    ]
