# Generated by Django 6.0 on 2026-09-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_pipeline', '0007_pipelinerun_api_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='schedule_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
    ]
