# Generated by Django 6.0 on 2026-09-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_pipeline', '0008_pipelinerun_schedule_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='parent_job_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='parent_pipeline_run_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
    ]
