# Generated by Django 6.0 on 2026-09-01 18:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('description', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('members_only', 'Privado'), ('company', 'Público')], default='members_only', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('in_progress', 'En proceso'), ('inactive', 'Inactivo'), ('archived', 'Archivado')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='company.company')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan programado',
                'verbose_name_plural': 'Planes programados',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('schedule.created', 'Creado'), ('schedule.updated', 'Actualizado'), ('schedule.paused', 'Pausado'), ('schedule.resumed', 'Reanudado'), ('schedule.archived', 'Archivado')], max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_audit_events', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_audit_events', to='company.company')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='file_scheduler.schedule')),
            ],
            options={
                'verbose_name': 'Evento de auditoría de plan',
                'verbose_name_plural': 'Eventos de auditoría de plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('PA', 'Admin de plan'), ('ED', 'Editor'), ('GE', 'Ejecutor'), ('CO', 'Consulta')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='file_scheduler.schedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membresía de plan',
                'verbose_name_plural': 'Membresías de plan',
            },
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['company', 'slug'], name='file_schedu_company_862d84_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['company', 'status'], name='file_schedu_company_26195a_idx'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('company', 'slug'), name='file_scheduler_company_slug_uniq'),
        ),
        migrations.AddIndex(
            model_name='scheduleauditevent',
            index=models.Index(fields=['schedule', '-created_at'], name='file_schedu_schedul_f59f63_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulemembership',
            index=models.Index(fields=['schedule', 'user', 'is_active'], name='file_schedu_schedul_f919a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='schedulemembership',
            constraint=models.UniqueConstraint(fields=('schedule', 'user'), name='file_scheduler_membership_user_uniq'),
        ),
    ]
