# Generated by Django 6.0 on 2026-09-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='cron_expr',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='schedule',
            name='day_of_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='day_of_week',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='monthly_mode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='schedule',
            name='programming_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_kind',
            field=models.CharField(blank=True, choices=[('daily', 'Diario'), ('weekdays', 'Lunes a viernes'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('cron', 'Cron')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_local',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='schedule',
            name='timezone',
            field=models.CharField(blank=True, default='America/Caracas', max_length=64),
        ),
    ]
