# Generated by Django 6.0 on 2026-09-01 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_pipeline', '0007_pipelinerun_api_client_id'),
        ('file_scheduler', '0002_schedule_cron_expr_schedule_day_of_month_and_more'),
        ('projects', '0009_add_role_consulta_generar'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='artifact_ref',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='schedule',
            name='input_origin',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='schedule',
            name='pipeline_inputs_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='published_version_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='target_kind',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='schedule',
            name='target_mode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='schedule',
            name='target_pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduler_plans', to='file_pipeline.pipelinedefinition'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='target_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduler_plans', to='projects.project'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='target_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='watch_id',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
    ]
