# Generated by Django 6.0 on 2026-09-01 19:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('file_scheduler', '0003_schedule_target_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleauditevent',
            name='event',
            field=models.CharField(choices=[('schedule.created', 'Creado'), ('schedule.updated', 'Actualizado'), ('schedule.paused', 'Pausado'), ('schedule.resumed', 'Reanudado'), ('schedule.archived', 'Archivado'), ('schedule.tick_enqueued', 'Tick encolado'), ('schedule.tick_skipped', 'Tick omitido'), ('schedule.tick_failed', 'Tick fallido')], max_length=40),
        ),
        migrations.CreateModel(
            name='ScheduleTick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('enqueued', 'Encolado'), ('skipped', 'Omitido'), ('failed', 'Falló')], max_length=20)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('user_message', models.CharField(blank=True, default='', max_length=400)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64)),
                ('job_id', models.CharField(blank=True, default='', max_length=36)),
                ('pipeline_run_id', models.CharField(blank=True, default='', max_length=36)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_ticks', to='company.company')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticks', to='file_scheduler.schedule')),
            ],
            options={
                'verbose_name': 'Tick de plan',
                'verbose_name_plural': 'Ticks de plan',
                'ordering': ['-scheduled_for'],
                'indexes': [models.Index(fields=['schedule', '-scheduled_for'], name='file_schedu_schedul_1fda67_idx'), models.Index(fields=['company', '-scheduled_for'], name='file_schedu_company_3bb9f1_idx')],
                'constraints': [models.UniqueConstraint(fields=('schedule', 'scheduled_for'), name='file_scheduler_tick_slot_uniq')],
            },
        ),
    ]
