# Generated by Django 6.0 on 2026-09-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_scheduler', '0004_alter_scheduleauditevent_event_scheduletick'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='overlap_policy',
            field=models.CharField(choices=[('skip', 'Omitir'), ('queue', 'Encolar detrás'), ('cancel_previous', 'Cancelar el anterior')], default='skip', max_length=20),
        ),
        migrations.AddField(
            model_name='schedule',
            name='overlap_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
