# Generated by Django 6.0 on 2026-09-01 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('file_pipeline', '0009_pipelinerun_parent_job_id_and_more'),
        ('file_scheduler', '0005_schedule_overlap_policy'),
        ('projects', '0009_add_role_consulta_generar'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scheduletick',
            name='file_scheduler_tick_slot_uniq',
        ),
        migrations.AddField(
            model_name='schedule',
            name='dependency_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='on_parent',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='schedule',
            name='parent_kind',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='schedule',
            name='parent_pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduler_child_plans', to='file_pipeline.pipelinedefinition'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='parent_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduler_child_plans', to='projects.project'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='trigger_mode',
            field=models.CharField(choices=[('time', 'Reloj'), ('dependency', 'Dependencia')], default='time', max_length=20),
        ),
        migrations.AddField(
            model_name='scheduletick',
            name='parent_job_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='scheduletick',
            name='parent_pipeline_run_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AddConstraint(
            model_name='scheduletick',
            constraint=models.UniqueConstraint(condition=models.Q(('parent_job_id', ''), ('parent_pipeline_run_id', '')), fields=('schedule', 'scheduled_for'), name='file_scheduler_tick_slot_uniq'),
        ),
        migrations.AddConstraint(
            model_name='scheduletick',
            constraint=models.UniqueConstraint(condition=models.Q(('parent_job_id', ''), _negated=True), fields=('schedule', 'parent_job_id'), name='file_scheduler_tick_parent_job_uniq'),
        ),
        migrations.AddConstraint(
            model_name='scheduletick',
            constraint=models.UniqueConstraint(condition=models.Q(('parent_pipeline_run_id', ''), _negated=True), fields=('schedule', 'parent_pipeline_run_id'), name='file_scheduler_tick_parent_run_uniq'),
        ),
    ]
