# Generated by Django 6.0 on 2026-09-01 20:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_scheduler', '0006_remove_scheduletick_file_scheduler_tick_slot_uniq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='notify_channel',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='schedule',
            name='notify_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='notify_on_run_failed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='notify_on_skip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='notify_on_tick_failed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='notify_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='notify_user_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='schedule',
            name='notify_webhook_secret',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='schedule',
            name='notify_webhook_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='scheduleauditevent',
            name='event',
            field=models.CharField(choices=[('schedule.created', 'Creado'), ('schedule.updated', 'Actualizado'), ('schedule.paused', 'Pausado'), ('schedule.resumed', 'Reanudado'), ('schedule.archived', 'Archivado'), ('schedule.tick_enqueued', 'Tick encolado'), ('schedule.tick_skipped', 'Tick omitido'), ('schedule.tick_failed', 'Tick fallido'), ('schedule.notify_sent', 'Aviso enviado')], max_length=40),
        ),
        migrations.CreateModel(
            name='ScheduleNotifyDispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('tick_failed', 'Tick fallido'), ('tick_skipped', 'Tick omitido'), ('run_failed', 'Run fallido')], max_length=20)),
                ('ref_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_dispatches', to='file_scheduler.schedule')),
            ],
            options={
                'verbose_name': 'Envío de aviso de plan',
                'verbose_name_plural': 'Envíos de aviso de plan',
                'constraints': [models.UniqueConstraint(fields=('schedule', 'kind', 'ref_id'), name='file_scheduler_notify_ref_uniq')],
            },
        ),
    ]
