# Generated by Django 6.0 on 2026-07-06 02:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text_short', 'Texto corto'), ('text_long', 'Texto largo'), ('integer', 'Entero'), ('decimal', 'Decimal'), ('date', 'Fecha'), ('datetime', 'Fecha y hora'), ('boolean', 'Sí / No'), ('select', 'Lista de opciones')], max_length=30)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('max_length', models.PositiveIntegerField(blank=True, null=True)),
                ('required', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_definitions', to='projects.project')),
            ],
            options={
                'verbose_name': 'Definición de campo',
                'verbose_name_plural': 'Definiciones de campo',
                'ordering': ['sort_order', 'label'],
                'constraints': [models.UniqueConstraint(fields=('project', 'key'), name='fields_fielddefinition_project_key_uniq')],
            },
        ),
    ]
